"""report_legal_source_status — read-only Studio-review report of legal sources.

Consolidates the status of every ``LegalSource`` and whether it is
*calculation-ready* (backs an APPROVED ``CompensationDataset``). Strictly
read-only: no DB writes, no network, no PII, no secrets. Safe to run any time.

CLI::

    python manage.py report_legal_source_status
    python manage.py report_legal_source_status --country IT
    python manage.py report_legal_source_status --format json
    python manage.py report_legal_source_status --format markdown --output docs/legal_sources/LEGAL_SOURCE_STATUS_2026-06-22.md

Cardinal rule surfaced by the report: ``approved`` means the source DOCUMENT is
authenticated, NOT that a public calculation is active. Only a source backing
an APPROVED dataset is ``calculation_ready``.
"""

from __future__ import annotations

import json
from pathlib import Path

from django.core.management.base import BaseCommand

from apps.legal_sources.status_report import build_report


class Command(BaseCommand):
    help = (
        "Read-only report of LegalSource status and calculation-readiness "
        "for Studio review. No DB writes, no network."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--country",
            default=None,
            help="Filter by ISO country code (e.g. IT, FR, BE, MA, TN, EU).",
        )
        parser.add_argument(
            "--format",
            choices=("text", "json", "markdown"),
            default="text",
            help="Output format. Default: text.",
        )
        parser.add_argument(
            "--output",
            default=None,
            help="Write the report to this file instead of stdout.",
        )

    def handle(self, *args, **options):
        report = build_report(country=options.get("country"))
        fmt = options["format"]

        if fmt == "json":
            rendered = json.dumps(report, indent=2, ensure_ascii=False)
        elif fmt == "markdown":
            rendered = _render_markdown(report)
        else:
            rendered = _render_text(report)

        output = options.get("output")
        if output:
            path = Path(output)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered + "\n", encoding="utf-8")
            self.stdout.write(f"[ok] wrote {fmt} report to {output}")
        else:
            self.stdout.write(rendered)


def _render_text(report: dict) -> str:
    lines: list[str] = []
    t = report["totals"]
    lines.append("LEGAL SOURCE STATUS — Studio review report")
    lines.append(
        f"sources={t['sources']}  approved={t['approved_sources']}  "
        f"calculation_ready={t['calculation_ready']}  "
        f"requires_legal_review={t['requires_legal_review']}"
    )
    lines.append("")
    for country, cs in report["summaries"].items():
        by = ", ".join(f"{k}={v}" for k, v in sorted(cs["by_status"].items()))
        lines.append(
            f"[{country}] total={cs['total']}  approved={cs['approved_sources']}  "
            f"calc_ready={cs['calculation_ready']}  needs_review={cs['requires_legal_review']}  "
            f"({by})"
        )
    lines.append("")
    for r in report["rows"]:
        ready = "CALC-READY" if r["calculation_ready"] else "no-calc"
        review = "REVIEW" if r["requires_legal_review"] else "approved"
        lines.append(
            f"  {r['country']} {r['slug']}\n"
            f"      {r['title']}\n"
            f"      type={r['source_type']} status={r['status']} reliability={r['reliability']} "
            f"[{ready}] [{review}]\n"
            f"      url={r['official_url']}\n"
            f"      pub={r['publication_date']} eff={r['effective_date']} until={r['valid_until'] or '—'} "
            f"checked={r['last_checked_at'] or '—'}\n"
            f"      versions={r['version_count']} attachments={r['attachment_count']} "
            f"(hashed={r['hashed_attachment_count']})"
        )
    return "\n".join(lines)


def _render_markdown(report: dict) -> str:
    t = report["totals"]
    lines: list[str] = []
    lines.append("# Legal Source Status — Studio review report")
    lines.append("")
    lines.append(
        "> Read-only snapshot generated by "
        "`python manage.py report_legal_source_status --format markdown`. "
        "`approved` means the source **document** is authenticated; only a "
        "source backing an APPROVED dataset is **calculation-ready**."
    )
    lines.append("")
    lines.append(
        f"**Totals:** sources={t['sources']} · approved={t['approved_sources']} · "
        f"calculation_ready={t['calculation_ready']} · "
        f"requires_legal_review={t['requires_legal_review']}"
    )
    lines.append("")
    lines.append("## Per-country summary")
    lines.append("")
    lines.append("| Country | Total | Approved | Calc-ready | Needs review |")
    lines.append("|:---:|---:|---:|---:|---:|")
    for country, cs in report["summaries"].items():
        lines.append(
            f"| {country} | {cs['total']} | {cs['approved_sources']} | "
            f"{cs['calculation_ready']} | {cs['requires_legal_review']} |"
        )
    lines.append("")
    lines.append("## Sources")
    lines.append("")
    lines.append(
        "| Country | Slug | Type | Status | Reliability | Calc-ready | Versions | Attach (hashed) |"
    )
    lines.append("|---|---|---|:---:|:---:|:---:|---:|---:|")
    for r in report["rows"]:
        ready = "✅" if r["calculation_ready"] else "—"
        lines.append(
            f"| {r['country']} | `{r['slug']}` | {r['source_type']} | {r['status']} | "
            f"{r['reliability']} | {ready} | {r['version_count']} | "
            f"{r['attachment_count']} ({r['hashed_attachment_count']}) |"
        )
    return "\n".join(lines)
