# Generated by Django 5.2.13 on 2026-04-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice ISO 3166-1 alpha-2, es. IT, FR, BE, MA, TN.",
                        max_length=2,
                        unique=True,
                        verbose_name="ISO alpha-2 code",
                    ),
                ),
                (
                    "code_alpha3",
                    models.CharField(
                        blank=True,
                        help_text="Codice ISO 3166-1 alpha-3, opzionale.",
                        max_length=3,
                        verbose_name="ISO alpha-3 code",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se False, il paese non viene proposto nei wizard pubblici.",
                        verbose_name="active",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice ISO 4217, es. EUR, MAD, TND, USD.",
                        max_length=3,
                        unique=True,
                        verbose_name="ISO 4217 code",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("symbol", models.CharField(blank=True, max_length=8, verbose_name="symbol")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Codice ISO 639-1, es. it, fr, en, ar.",
                        max_length=8,
                        unique=True,
                        verbose_name="ISO 639-1 code",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificatore interno stabile, es. IT, IT-LOM, FR, BE, MA, TN.",
                        max_length=32,
                        unique=True,
                        verbose_name="internal code",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "legal_system",
                    models.CharField(
                        choices=[
                            ("civil_law", "Civil law"),
                            ("common_law", "Common law"),
                            ("mixed", "Mixed system"),
                            ("religious", "Religious-based"),
                            ("unknown", "Unknown / not classified"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="legal system",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurisdictions",
                        to="jurisdictions.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurisdictions",
                        to="jurisdictions.currency",
                        verbose_name="default currency",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurisdictions",
                        to="jurisdictions.language",
                        verbose_name="default language",
                    ),
                ),
            ],
            options={
                "verbose_name": "jurisdiction",
                "verbose_name_plural": "jurisdictions",
                "ordering": ["code"],
            },
        ),
    ]
