# Generated by Django 5.2.13 on 2026-04-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jurisdictions", "0001_initial"),
        ("legal_sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("road_accident_bodily_injury", "Road accident — bodily injury"),
                            ("medical_malpractice", "Medical malpractice"),
                            ("work_injury", "Work injury"),
                            ("death_compensation", "Death compensation"),
                            ("parental_loss", "Parental loss"),
                            ("patrimonial_damage", "Patrimonial damage"),
                            ("inheritance_basic", "Inheritance — basic"),
                            ("international_inheritance", "Inheritance — international"),
                            ("generic_legal_assessment", "Generic legal assessment"),
                        ],
                        db_index=True,
                        help_text="Tipo di caso a cui il dataset si applica. Determina quale calculator può eventualmente leggerlo.",
                        max_length=64,
                        verbose_name="case type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Etichetta umana, es. 'Tabella Unica Nazionale 2025'.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "version_label",
                    models.CharField(
                        blank=True,
                        help_text="Versione interna, es. '2025.1'.",
                        max_length=64,
                        verbose_name="version label",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="valid from")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="valid to")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensation_datasets",
                        to="jurisdictions.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensation_datasets",
                        to="jurisdictions.jurisdiction",
                        verbose_name="jurisdiction",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Fonte legale da cui i dati sono estratti.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensation_datasets",
                        to="legal_sources.legalsource",
                        verbose_name="legal source",
                    ),
                ),
            ],
            options={
                "verbose_name": "compensation dataset",
                "verbose_name_plural": "compensation datasets",
                "ordering": ["-valid_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="CalculationFormula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificatore stabile, es. 'tun_biologico_punto'.",
                        max_length=64,
                        verbose_name="internal code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "expression_text",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione testuale della formula, riprodotta dalla fonte. Non viene valutata automaticamente: serve come traccia.",
                        verbose_name="expression text",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mappa parametri opzionale, JSON libero.",
                        verbose_name="parameters",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Riferimento testuale alla porzione di fonte da cui la formula è stata estratta, es. 'art. 138 comma 2'.",
                        max_length=255,
                        verbose_name="source reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulas",
                        to="compensation.compensationdataset",
                        verbose_name="dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "calculation formula",
                "verbose_name_plural": "calculation formulas",
                "ordering": ["dataset", "code"],
            },
        ),
        migrations.CreateModel(
            name="CompensationTableRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "row_type",
                    models.CharField(
                        blank=True,
                        help_text="Categoria libera della riga, es. 'point_value', 'daily_temporary_disability', 'multiplier'.",
                        max_length=64,
                        verbose_name="row type",
                    ),
                ),
                (
                    "age_min",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="age min"),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="age max"),
                ),
                (
                    "disability_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="disability % min"
                    ),
                ),
                (
                    "disability_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="disability % max"
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="point value",
                    ),
                ),
                (
                    "daily_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="daily amount",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=14,
                        null=True,
                        verbose_name="coefficient",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Campi opzionali specifici della tabella, JSON libero.",
                        verbose_name="extra",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="compensation.compensationdataset",
                        verbose_name="dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "compensation table row",
                "verbose_name_plural": "compensation table rows",
                "ordering": ["dataset", "age_min", "disability_min"],
            },
        ),
        migrations.AddIndex(
            model_name="compensationdataset",
            index=models.Index(
                fields=["jurisdiction", "case_type", "status"],
                name="compensatio_jurisdi_b5c519_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compensationdataset",
            index=models.Index(
                fields=["country", "case_type", "status"], name="compensatio_country_a21d4f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="calculationformula",
            constraint=models.UniqueConstraint(
                fields=("dataset", "code"), name="uniq_formula_code_per_dataset"
            ),
        ),
        migrations.AddIndex(
            model_name="compensationtablerow",
            index=models.Index(
                fields=["dataset", "row_type"], name="compensatio_dataset_f709a3_idx"
            ),
        ),
    ]
