# Generated by Django 5.2.13 on 2026-04-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0001_initial"),
        ("legal_sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pdf_attach", "PDF attached"),
                            ("csv_import", "CSV import"),
                            ("manual", "Manual entry"),
                        ],
                        max_length=24,
                        verbose_name="method",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=1024, verbose_name="file path"),
                ),
                (
                    "file_sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="file sha256"),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="file size (bytes)"),
                ),
                (
                    "rows_imported",
                    models.PositiveIntegerField(default=0, verbose_name="rows imported"),
                ),
                (
                    "rows_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="rows skipped"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                        verbose_name="result",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Può essere null se l'estrazione non è arrivata a creare il dataset (es. errore durante l'attach del PDF).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extraction_logs",
                        to="compensation.compensationdataset",
                        verbose_name="dataset",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extraction_logs",
                        to="legal_sources.legalsource",
                        verbose_name="legal source",
                    ),
                ),
            ],
            options={
                "verbose_name": "extraction log",
                "verbose_name_plural": "extraction logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "-created_at"], name="compensatio_source__4e9576_idx"
                    ),
                    models.Index(
                        fields=["dataset", "-created_at"], name="compensatio_dataset_6acc84_idx"
                    ),
                ],
            },
        ),
    ]
