# Generated by Django 5.2.13 on 2026-04-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0002_extractionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractionlog",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "extraction log",
                "verbose_name_plural": "extraction logs",
            },
        ),
    ]
