# Generated by Django 5.2.13 on 2026-06-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0003_alter_extractionlog_options"),
        ("jurisdictions", "0001_initial"),
        ("legal_sources", "0002_legalsourceversion_validity_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationdataset",
            name="source_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Versione specifica della fonte da cui i dati sono trascritti.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compensation_datasets",
                to="legal_sources.legalsourceversion",
                verbose_name="legal source version",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationdataset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="compdataset_valid_to_gte_valid_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationtablerow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_min__isnull", True),
                    ("age_max__isnull", True),
                    ("age_max__gte", models.F("age_min")),
                    _connector="OR",
                ),
                name="comprow_age_max_gte_age_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationtablerow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("disability_min__isnull", True),
                    ("disability_max__isnull", True),
                    ("disability_max__gte", models.F("disability_min")),
                    _connector="OR",
                ),
                name="comprow_disability_max_gte_disability_min",
            ),
        ),
    ]
