# Generated by Django 5.2.13 on 2026-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0005_link_approved_dataset_source_versions"),
        ("jurisdictions", "0001_initial"),
        ("legal_sources", "0002_legalsourceversion_validity_check"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="compensationdataset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "approved"), _negated=True),
                    ("source_version__isnull", False),
                    _connector="OR",
                ),
                name="compdataset_approved_requires_source_version",
            ),
        ),
    ]
