"""
Modelli `apps.reports`.

`SimulationReport` rappresenta un PDF generato a partire da una
`Simulation`. È un artefatto **derivato e immutabile** della Simulation:

- non riesegue alcun calcolo;
- legge `Simulation.output_data` / `sources_snapshot` / `input_data` e
  produce un PDF che riproduce esattamente lo stato persistito;
- ogni file generato è ancorato al record con `file_hash` SHA-256 in
  modo che si possa dimostrare che un certo PDF corrisponde a una
  certa Simulation in un certo istante.

Idempotenza: la generazione del PDF è gestita dal service layer. Per
default un nuovo PDF viene creato a ogni richiesta (audit completo);
i `SimulationReport` sono append-only.
"""

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


def report_upload_path(instance: SimulationReport, filename: str) -> str:
    return f"reports/simulations/{instance.simulation.public_id}/{filename}"


class SimulationReport(models.Model):
    """PDF generato per una `Simulation`. Append-only / immutabile."""

    class Status(models.TextChoices):
        GENERATED = "generated", _("Generated")
        FAILED = "failed", _("Failed")

    public_id = models.UUIDField(
        _("public id"),
        default=uuid.uuid4,
        editable=False,
        unique=True,
    )

    simulation = models.ForeignKey(
        "cases.Simulation",
        on_delete=models.PROTECT,
        related_name="reports",
        verbose_name=_("simulation"),
    )

    language = models.CharField(_("language"), max_length=8, default="it")

    file = models.FileField(
        _("file"),
        upload_to=report_upload_path,
        max_length=512,
    )
    file_hash = models.CharField(_("file sha256"), max_length=64, blank=True)
    file_size_bytes = models.PositiveBigIntegerField(_("file size (bytes)"), default=0)

    generated_at = models.DateTimeField(_("generated at"), auto_now_add=True)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="generated_simulation_reports",
        verbose_name=_("generated by"),
        null=True,
        blank=True,
    )

    status = models.CharField(
        _("status"),
        max_length=16,
        choices=Status.choices,
        default=Status.GENERATED,
        db_index=True,
    )
    error_message = models.TextField(_("error message"), blank=True)
    metadata = models.JSONField(_("metadata"), default=dict, blank=True)

    class Meta:
        verbose_name = _("simulation report")
        verbose_name_plural = _("simulation reports")
        # `-pk` come tiebreak deterministico: `auto_now_add` su Windows ha
        # risoluzione ~15.6ms (stesso pattern usato in cases.SimulationEvent).
        ordering = ["-generated_at", "-pk"]
        indexes = [
            models.Index(fields=["simulation", "-generated_at"]),
            models.Index(fields=["status", "-generated_at"]),
        ]

    def __str__(self) -> str:
        # Niente PII: solo il public_id del report e quello della simulazione.
        return f"report:{self.public_id} sim:{self.simulation.public_id}"
