# Generated by Django 5.2.13 on 2026-04-26 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("jurisdictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=64, verbose_name="session key"),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("road_accident_bodily_injury", "Road accident — bodily injury"),
                            ("medical_malpractice", "Medical malpractice"),
                            ("work_injury", "Work injury"),
                            ("death_compensation", "Death compensation"),
                            ("parental_loss", "Parental loss"),
                            ("patrimonial_damage", "Patrimonial damage"),
                            ("inheritance_basic", "Inheritance — basic"),
                            ("international_inheritance", "Inheritance — international"),
                            ("generic_legal_assessment", "Generic legal assessment"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="case type",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("it", "Italiano"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="it",
                        max_length=4,
                        verbose_name="locale",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, default=dict, verbose_name="input data"),
                ),
                (
                    "output_data",
                    models.JSONField(blank=True, default=dict, verbose_name="output data"),
                ),
                (
                    "sources_snapshot",
                    models.JSONField(blank=True, default=list, verbose_name="sources snapshot"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "unavailable_requires_legal_validation",
                                "Unavailable — requires legal validation",
                            ),
                            ("insufficient_input", "Insufficient input"),
                            ("calculated", "Calculated"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="unavailable_requires_legal_validation",
                        max_length=64,
                        verbose_name="status",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="low",
                        max_length=16,
                        verbose_name="confidence",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, verbose_name="currency")),
                (
                    "estimated_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="estimated min",
                    ),
                ),
                (
                    "estimated_mid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="estimated mid",
                    ),
                ),
                (
                    "estimated_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="estimated max",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="ip address"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=512, verbose_name="user agent"),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, max_length=512, verbose_name="source path"),
                ),
                (
                    "anonymized",
                    models.BooleanField(db_index=True, default=False, verbose_name="anonymized"),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="anonymized at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "consent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations",
                        to="compliance.consentrecord",
                        verbose_name="consent record",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="jurisdictions.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="jurisdictions.jurisdiction",
                        verbose_name="jurisdiction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "simulation",
                "verbose_name_plural": "simulations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("computed", "Computed"),
                            ("anonymized", "Anonymized"),
                            ("error", "Error"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                        verbose_name="event type",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=512, verbose_name="message")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cases.simulation",
                        verbose_name="simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "simulation event",
                "verbose_name_plural": "simulation events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["jurisdiction", "case_type"], name="cases_simul_jurisdi_fedbe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["status", "created_at"], name="cases_simul_status_ff98e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["user", "created_at"], name="cases_simul_user_id_365a89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["simulation", "event_type"], name="cases_simul_simulat_51d72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="cases_simul_event_t_7b8957_idx"
            ),
        ),
    ]
