# Generated by Django 5.2.13 on 2026-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationevent",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "simulation event",
                "verbose_name_plural": "simulation events",
            },
        ),
    ]
