# Generated by Django 5.2.13 on 2026-05-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_simulationevent_options'),
        ('compliance', '0003_staffsecurityalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='privacy consent timestamp'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='privacy_consent_given',
            field=models.BooleanField(default=False, verbose_name='privacy consent (GDPR art. 6) given'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='privacy_consent_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='privacy consent text version'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='special_categories_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='special categories consent timestamp'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='special_categories_consent_given',
            field=models.BooleanField(default=False, verbose_name='special categories consent (GDPR art. 9) given'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='special_categories_consent_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='special categories consent text version'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='consent_record',
            field=models.ForeignKey(blank=True, help_text="Backward-compatible FK al primo ConsentRecord (simulation_processing). Iter F-p0-leg-3-consent: il doppio consenso GDPR art. 6 + art. 9 e' tracciato anche tramite i campi denormalizzati privacy_*/special_categories_* sotto + un secondo ConsentRecord con purpose `special_categories_processing`.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='compliance.consentrecord', verbose_name='consent record'),
        ),
    ]
