# Generated by Django 5.2.13 on 2026-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_simulation_privacy_consent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='calculation_provenance',
            field=models.JSONField(blank=True, default=dict, verbose_name='calculation provenance'),
        ),
    ]
