# Generated by Django 5.2.13 on 2026-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_simulation_calculation_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("road_accident_bodily_injury", "Road accident — bodily injury"),
                    ("road_accident_microlesions", "Road accident — microlesions (art. 139)"),
                    (
                        "medical_liability_biological_damage",
                        "Medical liability — tabular biological damage",
                    ),
                    ("medical_malpractice", "Medical malpractice"),
                    ("work_injury", "Work injury"),
                    ("death_compensation", "Death compensation"),
                    ("parental_loss", "Parental loss"),
                    ("patrimonial_damage", "Patrimonial damage"),
                    ("inheritance_basic", "Inheritance — basic"),
                    ("international_inheritance", "Inheritance — international"),
                    ("generic_legal_assessment", "Generic legal assessment"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="case type",
            ),
        ),
    ]
