# Generated by Django 5.2.13 on 2026-04-26 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "required_for_simulation",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, il wizard di simulazione non può procedere senza.",
                        verbose_name="required for simulation",
                    ),
                ),
                (
                    "required_for_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, il lead form non può inviare senza.",
                        verbose_name="required for contact",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "consent purpose",
                "verbose_name_plural": "consent purposes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="code")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        help_text="Giorni dopo i quali il dato deve essere eliminato/anonymizzato.",
                        verbose_name="retention days",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("simulation_input", "Simulation inputs"),
                            ("simulation_result", "Simulation results"),
                            ("lead_contact", "Lead / contact requests"),
                            ("uploaded_document", "Uploaded documents"),
                            ("consent_log", "Consent records"),
                            ("audit_log", "Audit / privacy events"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="applies to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "data retention policy",
                "verbose_name_plural": "data retention policies",
                "ordering": ["applies_to", "code"],
            },
        ),
        migrations.CreateModel(
            name="ConsentTextVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Etichetta umana stabile, es. '2026-04' o '1.0'.",
                        max_length=32,
                        verbose_name="version",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("it", "Italiano"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        max_length=4,
                        verbose_name="language",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "effective_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="effective from"),
                ),
                (
                    "effective_to",
                    models.DateTimeField(blank=True, null=True, verbose_name="effective to"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_consent_text_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="text_versions",
                        to="compliance.consentpurpose",
                        verbose_name="purpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "consent text version",
                "verbose_name_plural": "consent text versions",
                "ordering": ["-effective_from", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=64, verbose_name="session key"),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="accepted")),
                ("accepted_at", models.DateTimeField(verbose_name="accepted at")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="ip address"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=512, verbose_name="user agent"),
                ),
                ("locale", models.CharField(blank=True, max_length=16, verbose_name="locale")),
                (
                    "source_path",
                    models.CharField(blank=True, max_length=512, verbose_name="source path"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="compliance.consentpurpose",
                        verbose_name="purpose",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "text_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Versione del testo che l'utente ha visto al momento del consenso.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="compliance.consenttextversion",
                        verbose_name="text version",
                    ),
                ),
            ],
            options={
                "verbose_name": "consent record",
                "verbose_name_plural": "consent records",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email di contatto, anche per richieste anonime senza account.",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("verifying_identity", "Verifying identity"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="requested at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                ("internal_notes", models.TextField(blank=True, verbose_name="internal notes")),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handled by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "data deletion request",
                "verbose_name_plural": "data deletion requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("consent_given", "Consent given"),
                            ("consent_withdrawn", "Consent withdrawn"),
                            ("data_accessed", "Data accessed"),
                            ("data_exported", "Data exported"),
                            ("data_deletion_requested", "Data deletion requested"),
                            ("data_deletion_completed", "Data deletion completed"),
                            ("legal_source_reviewed", "Legal source reviewed"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                        verbose_name="event type",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Es. 'cases.Simulation' o 'legal_sources.LegalSource'.",
                        max_length=128,
                        verbose_name="target model",
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(blank=True, max_length=64, verbose_name="target object id"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="ip address"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=512, verbose_name="user agent"),
                ),
                ("path", models.CharField(blank=True, max_length=512, verbose_name="path")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "privacy audit event",
                "verbose_name_plural": "privacy audit events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="consenttextversion",
            constraint=models.UniqueConstraint(
                fields=("purpose", "version", "language"), name="uniq_consent_text_version"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["purpose", "accepted"], name="compliance__purpose_3d4502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(fields=["user", "purpose"], name="compliance__user_id_63155e_idx"),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["session_key", "purpose"], name="compliance__session_e839d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyauditevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="compliance__event_t_4e80d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyauditevent",
            index=models.Index(
                fields=["target_model", "target_object_id"], name="compliance__target__6d44b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privacyauditevent",
            index=models.Index(
                fields=["actor", "created_at"], name="compliance__actor_i_6f095c_idx"
            ),
        ),
    ]
