# Generated by Django 5.2.13 on 2026-04-30 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login success"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="event type",
                    ),
                ),
                (
                    "username_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="username hash"
                    ),
                ),
                (
                    "ip_address_masked",
                    models.CharField(blank=True, max_length=64, verbose_name="ip address (masked)"),
                ),
                (
                    "user_agent_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="user agent hash"),
                ),
                ("path", models.CharField(blank=True, max_length=512, verbose_name="path")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_access_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "staff access event",
                "verbose_name_plural": "staff access events",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="compliance__event_t_0085af_idx"
                    ),
                    models.Index(
                        fields=["user", "event_type"], name="compliance__user_id_6837e5_idx"
                    ),
                ],
            },
        ),
    ]
