# Generated by Django 5.2.13 on 2026-04-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_staffaccessevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffSecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("admin_login_bruteforce", "Admin login brute-force")],
                        db_index=True,
                        max_length=64,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=16,
                        verbose_name="severity",
                    ),
                ),
                (
                    "username_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="username hash"
                    ),
                ),
                (
                    "ip_address_masked",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="ip address (masked)"
                    ),
                ),
                ("event_count", models.PositiveIntegerField(default=0, verbose_name="event count")),
                (
                    "window_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="window seconds"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="triggered at"
                    ),
                ),
                (
                    "cooldown_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="cooldown until"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
            ],
            options={
                "verbose_name": "staff security alert",
                "verbose_name_plural": "staff security alerts",
                "ordering": ["-triggered_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["alert_type", "triggered_at"], name="compliance__alert_t_8ae62e_idx"
                    ),
                    models.Index(
                        fields=["severity", "triggered_at"], name="compliance__severit_58e40e_idx"
                    ),
                    models.Index(
                        fields=["alert_type", "cooldown_until"],
                        name="compliance__alert_t_57cc08_idx",
                    ),
                ],
            },
        ),
    ]
