# Generated by Django 5.2.13 on 2026-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_staffsecurityalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="finished at"),
                ),
                ("policy_version", models.CharField(max_length=64, verbose_name="policy version")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("dry_run", "Dry run"),
                            ("anonymize", "Anonymize"),
                            ("delete", "Delete"),
                        ],
                        max_length=16,
                        verbose_name="mode",
                    ),
                ),
                ("dry_run", models.BooleanField(default=True, verbose_name="dry run")),
                (
                    "lead_candidates_count",
                    models.PositiveIntegerField(default=0, verbose_name="lead candidates"),
                ),
                (
                    "simulation_candidates_count",
                    models.PositiveIntegerField(default=0, verbose_name="simulation candidates"),
                ),
                (
                    "consent_candidates_count",
                    models.PositiveIntegerField(default=0, verbose_name="consent candidates"),
                ),
                (
                    "audit_candidates_count",
                    models.PositiveIntegerField(default=0, verbose_name="audit candidates"),
                ),
                (
                    "anonymized_count",
                    models.PositiveIntegerField(default=0, verbose_name="anonymized count"),
                ),
                (
                    "deleted_count",
                    models.PositiveIntegerField(default=0, verbose_name="deleted count"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                (
                    "executed_by",
                    models.CharField(
                        default="system",
                        help_text="system|manual|test|cron",
                        max_length=32,
                        verbose_name="executed by",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "retention run log",
                "verbose_name_plural": "retention run logs",
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(fields=["mode", "status"], name="compliance__mode_dcc5cb_idx"),
                    models.Index(
                        fields=["status", "started_at"], name="compliance__status_2e4389_idx"
                    ),
                ],
            },
        ),
    ]
