# Generated by Django 5.2.13 on 2026-05-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_simulation_privacy_consent_at_and_more"),
        ("compliance", "0004_retentionrunlog"),
        ("crm", "0004_lead_mandate_signed_lead_mandate_signed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MandateTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True, verbose_name="version")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working_copy", "Working copy"),
                            ("signed", "Signed"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="working_copy",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("signed_at", models.DateField(blank=True, null=True, verbose_name="signed at")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                (
                    "locale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("it", "Italiano"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        max_length=4,
                        verbose_name="locale",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "mandate template version",
                "verbose_name_plural": "mandate template versions",
                "ordering": ["-signed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "signed_at"], name="compliance__status_4d3cce_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MandateAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mandate_version",
                    models.CharField(max_length=64, verbose_name="mandate version"),
                ),
                ("accepted", models.BooleanField(default=False, verbose_name="accepted")),
                ("signed_at", models.DateTimeField(verbose_name="signed at")),
                (
                    "client_name_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the signer's name at signing time. May be left blank for offline signatures recorded in the physical file.",
                        max_length=160,
                        verbose_name="client name snapshot",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual entry by staff"),
                            ("upload", "Document upload"),
                            ("external_signature", "External signature provider"),
                            ("staff", "Marked by staff after offline signature"),
                        ],
                        default="staff",
                        max_length=24,
                        verbose_name="source",
                    ),
                ),
                ("locale", models.CharField(blank=True, max_length=16, verbose_name="locale")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandate_acceptances",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mandate_acceptances",
                        to="cases.simulation",
                        verbose_name="simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "mandate acceptance",
                "verbose_name_plural": "mandate acceptances",
                "ordering": ["-signed_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["mandate_version", "accepted"],
                        name="compliance__mandate_5431b1_idx",
                    ),
                    models.Index(
                        fields=["lead", "accepted"], name="compliance__lead_id_bbe1b6_idx"
                    ),
                    models.Index(
                        fields=["simulation", "accepted"], name="compliance__simulat_aac7a3_idx"
                    ),
                ],
            },
        ),
    ]
