# Generated by Django 5.2.13 on 2026-04-26 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_alter_simulationevent_options"),
        ("compliance", "0001_initial"),
        ("jurisdictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=64, verbose_name="session key"),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="first name")),
                ("last_name", models.CharField(max_length=80, verbose_name="last name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, verbose_name="phone number"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("it", "Italiano"),
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="it",
                        max_length=4,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("road_accident_bodily_injury", "Road accident — bodily injury"),
                            ("medical_malpractice", "Medical malpractice"),
                            ("work_injury", "Work injury"),
                            ("death_compensation", "Death compensation"),
                            ("parental_loss", "Parental loss"),
                            ("patrimonial_damage", "Patrimonial damage"),
                            ("inheritance_basic", "Inheritance — basic"),
                            ("international_inheritance", "Inheritance — international"),
                            ("generic_legal_assessment", "Generic legal assessment"),
                        ],
                        max_length=64,
                        verbose_name="case type",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=8,
                        verbose_name="priority",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="ip address"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=512, verbose_name="user agent"),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, max_length=512, verbose_name="source path"),
                ),
                (
                    "utm_source",
                    models.CharField(blank=True, max_length=128, verbose_name="utm source"),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, max_length=128, verbose_name="utm medium"),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=128, verbose_name="utm campaign"),
                ),
                ("internal_notes", models.TextField(blank=True, verbose_name="internal notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "contacted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="contacted at"),
                ),
                (
                    "converted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="converted at"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "consent_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="compliance.consentrecord",
                        verbose_name="consent record",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="jurisdictions.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="cases.simulation",
                        verbose_name="simulation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LeadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                            ("note", "Note"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                        verbose_name="event type",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=512, verbose_name="message")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead event",
                "verbose_name_plural": "lead events",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status", "created_at"], name="crm_lead_status_18283c_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["priority", "status"], name="crm_lead_priorit_277e5e_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="crm_lead_assigne_36bf8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["country", "case_type"], name="crm_lead_country_f8aa8f_idx"),
        ),
        migrations.AddIndex(
            model_name="leadevent",
            index=models.Index(
                fields=["lead", "event_type"], name="crm_leadeve_lead_id_12cc53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="crm_leadeve_event_t_ff3f8d_idx"
            ),
        ),
    ]
