# Generated by Django 5.2.13 on 2026-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_lead_privacy_consent_at_lead_privacy_consent_given_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="anonymized",
            field=models.BooleanField(db_index=True, default=False, verbose_name="anonymized"),
        ),
        migrations.AddField(
            model_name="lead",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="anonymized at"),
        ),
    ]
