# Generated by Django 5.2.13 on 2026-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_lead_anonymized_lead_anonymized_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="mandate_signed",
            field=models.BooleanField(db_index=True, default=False, verbose_name="mandate signed"),
        ),
        migrations.AddField(
            model_name="lead",
            name="mandate_signed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="mandate signed at"),
        ),
        migrations.AddField(
            model_name="lead",
            name="mandate_source",
            field=models.CharField(
                blank=True,
                help_text="manual | upload | external_signature | staff",
                max_length=24,
                verbose_name="mandate source",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="mandate_status",
            field=models.CharField(
                choices=[
                    ("mandate_required", "Mandate required"),
                    ("mandate_sent", "Mandate sent"),
                    ("mandate_signed", "Mandate signed"),
                    ("mandate_declined", "Mandate declined"),
                ],
                db_index=True,
                default="mandate_required",
                max_length=24,
                verbose_name="mandate status",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="mandate_version",
            field=models.CharField(blank=True, max_length=64, verbose_name="mandate version"),
        ),
    ]
