# Generated by Django 5.2.13 on 2026-05-10 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_lead_mandate_signed_lead_mandate_signed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadWebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g. 'lead.created'.", max_length=64, verbose_name="event type"
                    ),
                ),
                (
                    "payload_version",
                    models.CharField(max_length=16, verbose_name="payload version"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Stable across retries. Receiver uses it to deduplicate if the dispatcher retries after a network split.",
                        max_length=128,
                        unique=True,
                        verbose_name="idempotency key",
                    ),
                ),
                (
                    "target_url_domain",
                    models.CharField(
                        blank=True,
                        help_text="Audit-friendly host snapshot of `CRM_WEBHOOK_URL` at enqueue time. Never the full URL nor any query string.",
                        max_length=255,
                        verbose_name="target url domain",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed (non-retriable)"),
                            ("dead", "Dead (max attempts reached)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                (
                    "max_attempts",
                    models.PositiveIntegerField(default=5, verbose_name="max attempts"),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="next attempt at"),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last attempt at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                (
                    "last_status_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="last HTTP status code"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        help_text="Short error class name + message excerpt.",
                        max_length=255,
                        verbose_name="last error",
                    ),
                ),
                (
                    "response_excerpt",
                    models.CharField(
                        blank=True,
                        help_text="First 500 bytes of the receiver response, for debugging.",
                        max_length=500,
                        verbose_name="response excerpt",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="crm.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead webhook delivery",
                "verbose_name_plural": "lead webhook deliveries",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"], name="crm_leadweb_status_d45325_idx"
                    ),
                    models.Index(
                        fields=["lead", "event_type"], name="crm_leadweb_lead_id_de6d14_idx"
                    ),
                ],
            },
        ),
    ]
