# Generated by Django 5.2.13 on 2026-04-26 09:21

import apps.legal_sources.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jurisdictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="title")),
                ("slug", models.SlugField(blank=True, max_length=200, verbose_name="slug")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official_law", "Official law / statute"),
                            ("ministry_decree", "Ministry decree"),
                            ("court_table", "Court compensation table"),
                            ("administrative_guideline", "Administrative guideline"),
                            ("insurance_reference", "Insurance reference"),
                            ("doctrine", "Doctrine / academic"),
                            ("internal_legal_note", "Internal legal note"),
                            ("demo_placeholder", "Demo / placeholder (non legal)"),
                        ],
                        default="official_law",
                        max_length=32,
                        verbose_name="source type",
                    ),
                ),
                (
                    "official_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="official URL"),
                ),
                (
                    "citation",
                    models.CharField(
                        blank=True,
                        help_text="Riferimento testuale stabile, es. 'D.Lgs. 209/2005, art. 139'.",
                        max_length=512,
                        verbose_name="citation / reference",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, null=True, verbose_name="publication date"),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="effective date"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="valid until"),
                ),
                (
                    "last_checked_at",
                    models.DateField(blank=True, null=True, verbose_name="last checked at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("extracted", "Extracted"),
                            ("needs_review", "Needs review"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "reliability",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="reliability",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_sources",
                        to="jurisdictions.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Giurisdizione specifica, se più precisa del paese.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_sources",
                        to="jurisdictions.jurisdiction",
                        verbose_name="jurisdiction",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_sources",
                        to="jurisdictions.language",
                        verbose_name="language",
                    ),
                ),
                (
                    "legal_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_legal_sources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="legal reviewer",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="legal_sources.legalsource",
                        verbose_name="replaced by",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="legal_sources.legalsource",
                        verbose_name="supersedes",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal source",
                "verbose_name_plural": "legal sources",
                "ordering": ["-publication_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="LegalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("request_changes", "Request changes"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("reopen", "Reopen"),
                        ],
                        max_length=24,
                        verbose_name="decision",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("extracted", "Extracted"),
                            ("needs_review", "Needs review"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        max_length=24,
                        verbose_name="previous status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("extracted", "Extracted"),
                            ("needs_review", "Needs review"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        max_length=24,
                        verbose_name="new status",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="legal_sources.legalsource",
                        verbose_name="legal source",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal review",
                "verbose_name_plural": "legal reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalSourceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.legal_sources.models.attachment_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, verbose_name="original filename"),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=128, verbose_name="mime type"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="size (bytes)"),
                ),
                ("sha256", models.CharField(blank=True, max_length=64, verbose_name="sha256")),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, verbose_name="description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="legal_sources.legalsource",
                        verbose_name="legal source",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal source attachment",
                "verbose_name_plural": "legal source attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalSourceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version_label",
                    models.CharField(
                        help_text="Etichetta umana, es. '2024.1' o 'Tabelle Milano 2024'.",
                        max_length=64,
                        verbose_name="version label",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 del contenuto canonico, per integrità.",
                        max_length=64,
                        verbose_name="content hash (sha256)",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="valid from")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="valid to")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="legal_sources.legalsource",
                        verbose_name="legal source",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="legal_sources.legalsourceversion",
                        verbose_name="supersedes",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal source version",
                "verbose_name_plural": "legal source versions",
                "ordering": ["-valid_from", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="legalsource",
            index=models.Index(fields=["country", "status"], name="legal_sourc_country_d81cb5_idx"),
        ),
        migrations.AddIndex(
            model_name="legalsource",
            index=models.Index(
                fields=["jurisdiction", "status"], name="legal_sourc_jurisdi_d00193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalsource",
            index=models.Index(
                fields=["source_type", "status"], name="legal_sourc_source__064cdd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalsourceversion",
            constraint=models.UniqueConstraint(
                fields=("source", "version_label"), name="uniq_source_version_label"
            ),
        ),
    ]
