# Generated by Django 5.2.13 on 2026-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_sources", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="legalsourceversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="lsv_valid_to_gte_valid_from",
            ),
        ),
    ]
