"""Audit hard-coded diagnostic strings across the calculator stack.

Iter: ``F-calculator-warning-strings-translatable-pass1``.

The MA / TN / FR / BE / IT engines historically wrote English warning
sentences inline in Python. This script walks the relevant files and:

1. Lists every distinct ``missing_documents`` slug used by the
   engines (audit-only — slugs are stable identifiers, not user
   strings).
2. Lists every multi-line warning string that begins with a known
   "Approved …" / "No approved …" / "An approved …" / "Required
   input …" / "Applicable-law …" prefix — these are the strings
   that need to be migrated to ``apps.calculators.diagnostics``.
3. Writes a markdown report at
   ``docs/architecture/CALCULATOR_DIAGNOSTIC_STRINGS_AUDIT.md``.

Read-only on the source tree. Run it any time to re-audit progress
on the migration.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TARGET_DIRS = [
    REPO_ROOT / "apps" / "calculators" / "engines",
    REPO_ROOT / "apps" / "compensation",
    REPO_ROOT / "apps" / "cases",
]
REPORT_PATH = REPO_ROOT / "docs" / "architecture" / "CALCULATOR_DIAGNOSTIC_STRINGS_AUDIT.md"

MISSING_DOC_RE = re.compile(r'missing_documents=\[\s*"([^"]+)"\s*\]')
WARNING_PREFIXES = (
    "No approved legal sources",
    "Approved legal sources are present",
    "Approved compensation dataset is present",
    "Approved formula declares",
    "An approved formula exists",
    "Required input fields are missing",
    "Approved formula does not declare",
    "estate_value",
    "No heir class",
    "Applicable-law context requires",
    "The approved formula declares an invalid",
    "Tunisia calculator engine not yet implemented",
    "Morocco calculator engine not yet implemented",
)


def _scan(path: Path) -> list[dict]:
    out: list[dict] = []
    text = path.read_text(encoding="utf-8")
    # missing_documents slugs
    for m in MISSING_DOC_RE.finditer(text):
        line = text[: m.start()].count("\n") + 1
        out.append(
            {
                "file": str(path.relative_to(REPO_ROOT)),
                "line": line,
                "kind": "slug",
                "value": m.group(1),
            }
        )
    # warning prefixes
    for i, ln in enumerate(text.splitlines(), start=1):
        for prefix in WARNING_PREFIXES:
            if (
                prefix in ln
                and ln.lstrip().startswith('"')
                or (prefix in ln and "warnings=" not in ln and ln.lstrip().startswith('"'))
            ):
                out.append(
                    {
                        "file": str(path.relative_to(REPO_ROOT)),
                        "line": i,
                        "kind": "warning_prefix",
                        "value": prefix,
                    }
                )
                break
    return out


def main() -> int:
    findings: list[dict] = []
    for d in TARGET_DIRS:
        if not d.exists():
            continue
        for p in d.rglob("*.py"):
            findings.extend(_scan(p))

    slugs = sorted({f["value"] for f in findings if f["kind"] == "slug"})
    by_file: dict[str, list[dict]] = {}
    for f in findings:
        by_file.setdefault(f["file"], []).append(f)

    lines = [
        "# Calculator diagnostic strings — audit",
        "",
        "Auto-generated by `scripts/audit_calculator_diagnostic_strings.py`.",
        "",
        f"## Stable `missing_documents` slugs ({len(slugs)} distinct)",
        "",
    ]
    for s in slugs:
        lines.append(f"- `{s}`")
    lines.append("")
    lines.append("## Per-file findings")
    lines.append("")
    for file, items in sorted(by_file.items()):
        lines.append(f"### `{file}`")
        lines.append("")
        for item in items:
            kind = item["kind"]
            value = item["value"]
            lines.append(f"- L{item['line']:4d}  `{kind}`  `{value}`")
        lines.append("")

    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[report] {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(f"[summary] {len(findings)} findings, {len(slugs)} distinct missing_documents slugs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
