"""Audit local CSS coverage against Tailwind-like classes used in templates.

Iter: ``F-frontend-remove-tailwind-cdn-runtime-pass2``.

Walks every ``templates/`` HTML file, extracts the class tokens that
look like Tailwind utilities, and checks each against the local
``static/css/site.css`` stylesheet. Writes a markdown report at
``docs/architecture/LOCAL_CSS_COVERAGE_AUDIT_PASS2.md``.

Read-only on the source tree. Exit code is 0 even when gaps are
found — the goal is visibility, not blocking. Critical gaps (layout
primitives) are flagged with `[CRITICAL]` so the engineer can act
on them.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIRS = [REPO_ROOT / "templates"]
SITE_CSS = REPO_ROOT / "static" / "css" / "site.css"
REPORT_PATH = REPO_ROOT / "docs" / "architecture" / "LOCAL_CSS_COVERAGE_AUDIT_PASS2.md"

# Anything that looks like a Tailwind utility — letters, digits,
# hyphens, colons (variant prefixes), brackets (arbitrary values),
# slashes (numeric fractions like 1/2), dots (responsive `.5`).
CLASS_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_:/\.\-\[\]]*")
# class="...", class='...', :class="..."
CLASS_ATTR_RE = re.compile(r"""class=(?P<q>['"])(?P<value>.*?)(?P=q)""", flags=re.DOTALL)

# Critical layout/typography primitives — gaps in these classes
# break the page visually. Reported with [CRITICAL] tag.
CRITICAL_PREFIXES = (
    "max-w-",
    "min-h-",
    "grid-cols-",
    "flex",
    "items-",
    "justify-",
    "gap-",
    "p-",
    "px-",
    "py-",
    "pt-",
    "pb-",
    "m-",
    "mx-",
    "my-",
    "mt-",
    "mb-",
    "rounded-",
    "shadow-",
    "border",
    "bg-",
    "text-",
    "font-",
    "leading-",
    "tracking-",
    "w-",
    "h-",
    "hidden",
    "block",
    "inline",
    "container",
    "sm:",
    "lg:",
)


def _scan_template_classes() -> dict[str, int]:
    """Return a counter of every class token seen across the templates."""
    counter: Counter[str] = Counter()
    for d in TEMPLATE_DIRS:
        for path in d.rglob("*.html"):
            text = path.read_text(encoding="utf-8")
            for m in CLASS_ATTR_RE.finditer(text):
                value = m.group("value")
                # Drop django template variables ({{...}}/{%...%})
                value = re.sub(r"{[%{][^}]+[%}]}", " ", value)
                for tok in value.split():
                    if CLASS_TOKEN_RE.fullmatch(tok):
                        counter[tok] += 1
    return dict(counter)


def _read_site_css() -> str:
    return SITE_CSS.read_text(encoding="utf-8") if SITE_CSS.exists() else ""


def _normalise_for_lookup(token: str) -> str:
    """Tailwind variants like `sm:grid-cols-2` are written as
    `.sm\\:grid-cols-2` in CSS. Build the literal selector form we
    expect to find in the file. Special characters that need
    backslash-escaping in CSS selectors: ``: . / [ ]``.
    """
    out = "."
    for ch in token:
        if ch in (":", ".", "/", "[", "]"):
            out += "\\" + ch
        else:
            out += ch
    return out


def _is_critical(token: str) -> bool:
    return any(token.startswith(prefix) for prefix in CRITICAL_PREFIXES)


def main() -> int:
    seen = _scan_template_classes()
    css = _read_site_css()

    covered: list[tuple[str, int]] = []
    missing: list[tuple[str, int]] = []
    for token, count in sorted(seen.items()):
        # Skip suspicious tokens (no hyphen + not a known keyword)
        if not any(c in token for c in "-:"):
            keyword_only = token in {
                "block",
                "inline",
                "flex",
                "grid",
                "hidden",
                "container",
                "underline",
                "uppercase",
                "italic",
                "relative",
                "absolute",
                "fixed",
                "sticky",
                "rounded",
                "border",
                "shadow",
                "transition",
            }
            if not keyword_only:
                continue
        sel = _normalise_for_lookup(token)
        if sel in css or token in css:
            covered.append((token, count))
        else:
            missing.append((token, count))

    critical_missing = [(t, c) for t, c in missing if _is_critical(t)]
    other_missing = [(t, c) for t, c in missing if not _is_critical(t)]

    lines = [
        "# Local CSS coverage audit — pass 2",
        "",
        "Auto-generated by `scripts/audit_local_css_coverage.py`.",
        "",
        f"Templates scanned: every `*.html` under `{TEMPLATE_DIRS[0].relative_to(REPO_ROOT)}/`.",
        f"CSS file: `{SITE_CSS.relative_to(REPO_ROOT)}` ({len(css)} bytes).",
        "",
        "## Summary",
        f"- Distinct utility classes used: {len(seen)}",
        f"- Covered by `site.css`: {len(covered)}",
        f"- Missing (informational): {len(missing)}",
        f"  - **CRITICAL** (layout/typography primitives): {len(critical_missing)}",
        f"  - other (utility / hover / arbitrary): {len(other_missing)}",
        "",
        "## CRITICAL gaps",
        "",
    ]
    if not critical_missing:
        lines.append("None — every layout-critical utility is mapped locally.")
        lines.append("")
    else:
        for token, count in sorted(critical_missing, key=lambda t: (-t[1], t[0])):
            lines.append(f"- [CRITICAL] `{token}` (used {count}×)")
        lines.append("")

    lines.append("## Other missing utilities (top 60 by frequency)")
    lines.append("")
    if not other_missing:
        lines.append("None.")
    else:
        for token, count in sorted(other_missing, key=lambda t: (-t[1], t[0]))[:60]:
            lines.append(f"- `{token}` (used {count}×)")
    lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[report] {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(
        f"[summary] {len(seen)} classes, {len(covered)} covered, "
        f"{len(missing)} missing ({len(critical_missing)} CRITICAL)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
