# Generated by Django 5.2.13 on 2026-04-27 07:53

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_alter_simulationevent_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                ("language", models.CharField(default="it", max_length=8, verbose_name="language")),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        upload_to=apps.reports.models.report_upload_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="file sha256"),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="file size (bytes)"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="generated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("generated", "Generated"), ("failed", "Failed")],
                        db_index=True,
                        default="generated",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="error message")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_simulation_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generated by",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="cases.simulation",
                        verbose_name="simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "simulation report",
                "verbose_name_plural": "simulation reports",
                "ordering": ["-generated_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["simulation", "-generated_at"],
                        name="reports_sim_simulat_a99db6_idx",
                    ),
                    models.Index(
                        fields=["status", "-generated_at"], name="reports_sim_status_4e8a8a_idx"
                    ),
                ],
            },
        ),
    ]
